index:
  path: _root
  redirect: senate

senate-curves-tsv:
  path: senate-curves-:date.tsv
  content-type: text/tab-separated-values; charset=utf-8
  collection: senate_races_for_tsv

senate-seat-counts-tsv:
  path: senate-seat-counts-:date.tsv
  content-type: text/tab-separated-values; charset=utf-8
  collection: senate_races_for_tsv

senate:
  path: senate
  model: senate

senate-race-svg:
  path: senate-race-:state_code.svg
  collection: senate_races
  content-type: image/svg+xml; charset=utf-8

sidebar:
  path: sidebar
  model: senate

sidebar-test:
  path: sidebar-test
