index:
  path: _root
  redirect: senate

senate:
  path: senate
  model: senate

senate-race-svg:
  path: senate-race-:state_code.svg
  collection: senate_races
  content-type: image/svg+xml; charset=utf-8

sidebar:
  path: sidebar
  model: senate

sidebar-test:
  path: sidebar-test
